version: "3.9"

services:
  backend:
    build: ./bookmark.backend

    command:
      - uvicorn
      - main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
    ports:
      - "8000:8000"

  frontend:
    build: ./bookmark.frontend
    command:
      - npm
      - run
      - dev
    ports:
      - "3000:3000"
